name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  run-dafny:
    runs-on: ubuntu-latest    
    steps:
        # Setup
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dafny-lang/setup-dafny-action@v1.7.0
        with:
          dafny-version: "4.6.0"
      - name: Set DAFNY_HOME
        run: echo "DAFNY_HOME=$(dirname $(which dafny))" >> $GITHUB_ENV
      - name: Verify
        run: dafny verify dfyconfig.toml
